%%{init: { 'logLevel': 'debug', 'theme': 'base' } }%%

timeline
    section Early Excitement
        1943 : Model of a neuron (McCulloch and Pitts)
        1957 : Perceptron Mark 1 (Frank Rosenblatt)
        1969 : Perceptrons (Minsky and Papert)
    section Backpropagation breakthrough
        1986 : Multilayer perceptrons (Rumelhart, Hinton and Williams)
        1989 : Backpropagation applied to handwritten zip codes (LeCun et al.)
    section Deep learning era
        2011 : GPU implementation (Cireşan et al.)
        2012 : AlexNet (Krizhevsky, Sutskever and Hinton)
